# Generated by Django 5.2.4 on 2025-08-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantlist', '0003_remove_restaurant_cuisine_remove_restaurant_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short title or description of the menu (e.g. 'Lunch Menu', 'Drinks')", max_length=100)),
                ('file_url', models.URLField(help_text='Direct URL to the menu file (image or PDF)')),
                ('page_number', models.PositiveIntegerField(blank=True, help_text='Optional page number for multi-page menus', null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurantlist.restaurant')),
            ],
        ),
    ]
