# Generated by Django 5.2.4 on 2025-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantlist', '0005_alter_menu_options_alter_cuisine_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='file_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a PDF or image file for this menu', null=True, upload_to='menus/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(help_text='Short title or description of the menu', max_length=100),
        ),
    ]
