# Generated by Django 5.2.4 on 2025-08-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantlist', '0006_remove_menu_file_url_menu_file_alter_menu_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurantlist.restaurant')),
            ],
            options={
                'ordering': ['restaurant__name', 'name'],
                'indexes': [models.Index(fields=['price'], name='restaurantl_price_3de611_idx')],
            },
        ),
    ]
