# Generated by Django 5.2.4 on 2025-08-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantlist', '0007_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Optional uploaded image for the restaurant', null=True, upload_to='restaurants/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_price_tag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_price_tag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
